apiVersion: apps/v1
kind: Deployment
metadata:
  name: will-app
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: will-app
  template:
    metadata:
      labels:
        app: will-app
    spec:
      containers:
      - name: wapp
        image: wil42/playground
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: will-app-service
  namespace: dev
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: will-app
---